#!/usr/bin/env bash
# Installs Nginxon a server

sudo apt-get update
sudo apt-get install -y nginx

sudo ufw allow 'Nginx HTTP'

rm /var/www/html/index.nginx-debian.html

echo "Holberton School" > /var/www/html/index.html
sudo nginx -t
sudo service nginx restart
