#!/usr/bin/env bash
# Redirects to another page

sudo apt-get update
sudo apt-get install -y nginx

sudo ufw allow 'Nginx HTTP'

string_for_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/Ngum12 permanent;"
sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default
